---
title: "Exercise1"
author: "sven panis"
date: "2024-04-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadPck, include=F}
library(tidyverse)
```

Create a fake RT + accuracy data set for 1 subject.

```{r createFakeData, echo=F}
set.seed(1234)
Trials_perCondition = 5
data <- tibble(pid   = 1,
               trial = sample(1:(Trials_perCondition*2)),
               condition = c(rep(1,Trials_perCondition), rep(2,Trials_perCondition)),
               RT = c(rnorm(Trials_perCondition, 600, 200), rexp(Trials_perCondition, 1/600)),
               acc = rep(sample(c(0,1), size=Trials_perCondition,replace=T, prob=c(.3,.7)),2)) %>% 
        arrange(trial)
print.data.frame(data)
```

Create right-censored observations and discrete RT variable.

```{r preprocess}
cutoff <- 500 # censoring time in ms
bin_size <- 100
data2 <- data %>%
         mutate(censor = 1) %>%
         mutate(RT2 = ifelse(RT > cutoff, cutoff, RT)) %>%
         mutate(censor = ifelse(RT2 == cutoff,0,censor)) %>%
         mutate(dRT = ceiling(RT2/bin_size))
print.data.frame(data2)
```

Create person-trial-period data set.

```{r ptbDataSet}
data_ptb <-
  data2 %>% 
  uncount(weights = dRT) %>% # duplicate rows according to a weighting variable (or expression).
  group_by(trial) %>% 
  mutate(period = 1:n()) %>% 
  mutate(event = if_else(period == max(period) & censor == 1, 1, 0)) %>% 
  select(-censor) %>% 
  ungroup()
print.data.frame(data_ptb)
```

Set-up life table.

```{r lifetable}
data_lt <-
  data_ptb %>% 
  mutate(event = str_c("event = ", event)) %>%
  group_by(condition,period) %>% 
  count(event) %>% 
  ungroup() %>% 
  pivot_wider(names_from = event,
              values_from = n) %>% 
  mutate(ev1 = ifelse(is.na(`event = 1`),0,`event = 1`)) %>%
  mutate(RS = `event = 0` + ev1) %>%
  mutate(hazard = (ev1 / RS) %>% round(digits = 4))

print.data.frame(data_lt)
```






