---
title: "packages"
author: "Sven Panis"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file installs packages.

# install the libraries that we will be using #

## install ##

general packages for data wrangling and visualisation used in various scripts

```{r}
install.packages(c("tidyverse", "RColorBrewer", "patchwork", "ggridges"))

install.packages("pracma") # for reshaping a Matrix

install.packages("ragg")
```

packages for model building in brms.

```{r}
install.packages("remotes")
#remotes::install_github("stan-dev/cmdstanr")

# we recommend running this in a fresh R session or restarting your current session
install.packages("cmdstanr", repos = c('https://stan-dev.r-universe.dev', getOption("repos")))

install_cmdstan(cores=8) 
check_cmdstan_toolchain() 

install.packages("devtools")
devtools::install_github("jmgirard/standist")
 
install.packages(c("brms", "tidybayes", "bayesplot", "future"))

install.packages("sn") # to sample from skew-normal distribution

install.packages("extraDistr")
```


packages for papaja and manuscript writing

```{r install-pkg}
# install.packages(c("devtools", "remotes"))
# 
# devtools::install_github("crsh/papaja")
# devtools::install_github("crsh/citr")
# 
# install.packages("tinytex")
# tinytex::install_tinytex()
# 
# # and now some useful addins for writing .Rmd from R Studio word count
# devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
# 
# # remedy for shortcuts in markdown writing
# remotes::install_github("ThinkR-open/remedy")
# 
# # grammar checking - cool...
# devtools::install_github("ropenscilabs/gramr")
```

use renv() to take a snapshot of installed packages and update the lock.file 

```{r snapshot-renv}
# take a snapshot and update the lock.file
renv::snapshot() # this is only necessary when new packages or installed or packages are updated.
```